### ISSUE TITLE
Setting storage persistent volume to enabled breaks json

### ISSUE THREAD

**Issue by a-nldisr** [dcos-labs/dcos-jupyterlab-service#17]
Setting  persistent volume causes:
```
Unable to parse the string as a JSON value
```

Changing the value to string in JSON causes:
```
Options JSON failed validation
```

DCOS version 1.11.x

Snippet of the JSON affected:
```
  "storage": {
    "persistence": {
      "host_volume_size": 4000,
      "enable": true
    }
  },
```

full JSON
```  
{
  "service": {
    "name": "/jupyterlab-notebook",
    "cmd": "/usr/local/bin/start.sh ${CONDA_DIR}/bin/jupyter lab --notebook-dir=${MESOS_SANDBOX}",
    "cpus": 2,
    "force_pull": false,
    "mem": 8192,
    "user": "nobody",
    "gpu_support": {
      "enabled": false,
      "gpus": 0
    }
  },
  "oidc": {
    "enable_oidc": false,
    "oidc_discovery_uri": "https://keycloak.example.com/auth/realms/notebook/.well-known/openid-configuration",
    "oidc_redirect_uri": "/oidc-redirect-callback",
    "oidc_client_id": "notebook",
    "oidc_client_secret": "b874f6e9-8f3f-41a6-a206-53e928d24fb1",
    "oidc_tls_verify": "no",
    "enable_windows": false,
    "oidc_use_email": false,
    "oidc_email": "user@example.com",
    "oidc_upn": "user007",
    "oidc_logout_path": "/logmeout",
    "oidc_post_logout_redirect_uri": "https://<VHOST>/<optional PATH_PREFIX>/<Service Name>",
    "oidc_use_spartan_resolver": true
  },
  "s3": {
    "aws_region": "us-east-1",
    "s3_endpoint": "s3.us-east-1.amazonaws.com",
    "s3_https": 1,
    "s3_ssl": 1
  },
  "spark": {
    "enable_spark_monitor": true,
    "spark_master_url": "mesos://zk://zk-1.zk:2181,zk-2.zk:2181,zk-3.zk:2181,zk-4.zk:2181,zk-5.zk:2181/mesos",
    "spark_driver_cores": 2,
    "spark_driver_memory": "6g",
    "spark_driver_java_options": "\"-server -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/mnt/mesos/sandbox\"",
    "spark_history_fs_logdirectory": "hdfs://hdfs/history",
    "spark_conf_spark_scheduler": "spark.scheduler.minRegisteredResourcesRatio=1.0",
    "spark_conf_cores_max": "spark.cores.max=5",
    "spark_conf_executor_cores": "spark.executor.cores=1",
    "spark_conf_executor_memory": "spark.executor.memory=6g",
    "spark_conf_executor_java_options": "spark.executor.extraJavaOptions=\"-server -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/mnt/mesos/sandbox\"",
    "spark_conf_eventlog_enabled": "spark.eventLog.enabled=false",
    "spark_conf_eventlog_dir": "spark.eventLog.dir=hdfs://hdfs/",
    "spark_conf_hadoop_fs_s3a_aws_credentials_provider": "spark.hadoop.fs.s3a.aws.credentials.provider=com.amazonaws.auth.InstanceProfileCredentialsProvider",
    "spark_conf_jars_packages": "spark.jars.packages=org.apache.spark:spark-streaming-kafka-0-10_2.11:2.2.1,org.apache.kafka:kafka_2.11:0.10.2.1",
    "spark_conf_mesos_executor_docker_image": "spark.mesos.executor.docker.image=dcoslabs/dcos-spark:1.11.4-2.2.1",
    "spark_conf_mesos_executor_home": "spark.mesos.executor.home=/opt/spark",
    "spark_conf_mesos_containerizer": "spark.mesos.containerizer=mesos",
    "spark_conf_mesos_driver_labels": "spark.mesos.driver.labels=DCOS_SPACE:",
    "spark_conf_mesos_task_labels": "spark.mesos.task.labels=DCOS_SPACE:",
    "spark_conf_executor_krb5_config": "spark.executorEnv.KRB5_CONFIG=/mnt/mesos/sandbox/krb5.conf",
    "spark_conf_executor_java_home": "spark.executorEnv.JAVA_HOME=/opt/jdk",
    "spark_conf_executor_hadoop_hdfs_home": "spark.executorEnv.HADOOP_HDFS_HOME=/opt/hadoop",
    "spark_conf_executor_hadoop_opts": "spark.executorEnv.HADOOP_OPTS=\"-Djava.library.path=/opt/hadoop/lib/native -Djava.security.krb5.conf=/mnt/mesos/sandbox/krb5.conf\"",
    "spark_conf_mesos_executor_docker_forcepullimage": "spark.mesos.executor.docker.forcePullImage=true",
    "spark_user": "nobody"
  },
  "storage": {
    "persistence": {
      "host_volume_size": 4000,
      "enable": true
    }
  },
  "networking": {
    "cni_support": {
      "enabled": true
    },
    "external_access": {
      "enabled": true,
      "external_public_agent_hostname": "somethinghere.com"
    }
  },
  "environment": {
    "secrets": false,
    "service_credential": "jupyterlab-notebook/serviceCredential",
    "conda_envs_path": "/mnt/mesos/sandbox/conda/envs:/opt/conda/envs",
    "conda_pkgs_dir": "/mnt/mesos/sandbox/conda/pkgs:/opt/conda/pkgs",
    "dcos_dir": "/mnt/mesos/sandbox/.dcos",
    "hadoop_conf_dir": "/mnt/mesos/sandbox",
    "home": "/mnt/mesos/sandbox",
    "java_opts": "\"-server -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/mnt/mesos/sandbox\"",
    "jupyter_conf_urls": "",
    "jupyter_config_dir": "/mnt/mesos/sandbox/.jupyter",
    "jupyter_password": "",
    "jupyter_runtime_dir": "/mnt/mesos/sandbox/.local/share/jupyter/runtime",
    "nginx_log_level": "warn",
    "start_dask_distributed": false,
    "start_ray_head_node": false,
    "start_spark_history_server": false,
    "start_tensorboard": false,
    "user": "nobody",
    "tensorboard_logdir": "hdfs://hdfs/",
    "term": "xterm-256color"
  }
}
```

**Comment by fabianbaier** [comment]
@a-nldisr thanks for reporting this. Should be fixed with the above PR.

**Comment by a-nldisr** [comment]
Cool i have some more questions regarding the setup, i suspect other tools are the cause but i want to ensure this is the case. What channel can i best ask this?

**Comment by a-nldisr** [comment]
Related to this, are there any plans to enable external (rexray, portworx) volume support?

**Comment by vishnu2kmohan** [comment]
@a-nldisr We're not enabling DVDI (REX-RAY) volumes in favor of Container Storage Interface (CSI) External Volume when it lands in subsequent releases of DC/OS.

Note: DVDI volumes are currently not supported for production use as the feature is in `Beta`: https://docs.mesosphere.com/1.11/storage/external-storage/

**Comment by vishnu2kmohan** [comment]
That said, support for [S3Contents](https://github.com/danielfrg/s3contents) (and [PGContents](https://github.com/quantopian/pgcontents)) will land once [pull/24](https://github.com/dcos-labs/dcos-jupyterlab-service/pull/24) is merged.

We also considered adding support for [HDFSContents](https://github.com/hopshadoop/hdfscontents) but [pydoop](https://github.com/crs4/pydoop) isn't ready for out-of-the-box [use with python3](https://github.com/crs4/pydoop/blob/develop/docs/installation.rst):
```
Collecting pydoop (from hdfscontents->-r /opt/conda/condaenv.b40ntw56.requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/75/75/085a6410b085f231328884ca3349287a8705822ad8afdca715401e5c4f33/pydoop-1.2.0.tar.gz (956kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-e734_r5y/pydoop/setup.py", line 45
        print 'using setuptools version', setuptools.__version__
                                       ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print('using setuptools version', setuptools.__version__)?
    
    ----------------------------------------
```

**Comment by a-nldisr** [comment]
Great! 👍

**Comment by rohithzr** [comment]
resurfaced on 
```
dcos --version
dcoscli.version=0.7.8
dcos.version=1.12.1
dcos.commit=aad01aaa24f90fd83b626acad5069e8328bbcac9
dcos.bootstrap-id=3299fd245aa4a6783a2ce753eabcf920553b2459
```

```
{
    "storage": {
        "persistence": {
            "host_volume_size": 4000,
            "enable": true
        }
    },
    "external_access": {
        "enabled": true,
        "external_public_agent_hostname": "jupyter.labroots.mydomain.com"
    },
    "environment": {
        "secrets": false,
        "service_credential": "jupyterlab-notebook/serviceCredential",
        "conda_envs_path": "/mnt/efs/mesos/sandbox/conda/envs:/opt/conda/envs",
        "conda_pkgs_dir": "/mnt/efs/mesos/sandbox/conda/pkgs:/opt/conda/pkgs",
        "dcos_dir": "/mnt/efs/mesos/sandbox/.dcos",
        "hadoop_conf_dir": "/mnt/efs/mesos/sandbox",
        "home": "/mnt/efs/mesos/sandbox",
        "java_opts": "'-server -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/mnt/efs/mesos/sandbox'",
        "jupyter_conf_urls": "http://api.hdfs.marathon.l4lb.thisdcos.directory/v1/endpoints",
        "jupyter_config_dir": "/mnt/efs/mesos/sandbox/.jupyter",
        "jupyter_password": "labroots",
        "jupyter_runtime_dir": "/mnt/efs/mesos/sandbox/.local/share/jupyter/runtime",
        "nginx_log_level": "warn",
        "start_dask_distributed": false,
        "start_ray_head_node": false,
        "user": "nobody",
        "tensorboard_logdir": "hdfs://hdfs/",
        "term": "xterm-256color",
        "start_spark_history_server": true,
        "start_tensorboard": true
    }
}
```
